Editorial: refactor processing to use ordered map
w3c/image-resource pull request #36
Opened 2021-03-05 04:11 UTC by marcoscaceres

2021-03-05 19:32 UTC, aarongustafson requested changes
LGTM with one change

2021-03-05 19:32 UTC, aarongustafson commented on index.html
> +            <li>Set |image|["type"] to the [=essence=] of |mine|.
mine -> mime

2021-03-05 19:33 UTC, aarongustafson commented
There are also several ReSpec errors that need resolution prior to merging.

2021-03-08 01:05 UTC, marcoscaceres commented on index.html
> +            <li>Set |image|["type"] to the [=essence=] of |mine|.
Missed opportunity! 
![Screen Shot 2021-03-08 at 12 05 35 pm](https://user-images.githubusercontent.com/870154/110262075-98ffeb80-8006-11eb-8e3b-d3883bae19ce.png)

2021-03-08 01:07 UTC, marcoscaceres commented
> There are also several ReSpec errors that need resolution prior to merging.

Will send a PR for those.

2021-03-12 19:38 UTC, aarongustafson approved these changes

2021-03-13 00:09 UTC, merged